services:
  backend:
    container_name: flask_backend
    build: .
    restart: always
    env_file: .env
    ports:
      - "3308:3308"
    volumes:
      - .:/app
    environment:
      - DOCKER=1
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=${FLASK_ENV}
    command: >
      sh -c "if [ \"$FLASK_ENV\" = 'development' ]; then
              flask run --host=0.0.0.0 --port=3308 --debug;
            else
              gunicorn -b 0.0.0.0:3308 'app:create_app()';
            fi"

  db:
    container_name: postgresql_db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
